//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ariadna
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.GameGenres = new HashSet<GameGenre>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string title_original { get; set; }
        public int year { get; set; }
        public string file_path { get; set; }
        public string version { get; set; }
        public Nullable<bool> want_to_play { get; set; }
        public Nullable<bool> vr { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameGenre> GameGenres { get; set; }
    }
}
