//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ariadna
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameGenre
    {
        public int Id { get; set; }
        public int gameId { get; set; }
        public int genreId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual GenreOfGame GenreOfGame { get; set; }
    }
}
