//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manina.Windows.Forms {
    using System;
    using System.Drawing;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImageListViewResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImageListViewResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manina.Windows.Forms.ImageListViewResources", typeof(ImageListViewResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperture.
        /// </summary>
        internal static string Aperture {
            get {
                return ResourceManager.GetString("Aperture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Artist.
        /// </summary>
        internal static string Artist {
            get {
                return ResourceManager.GetString("Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Access.
        /// </summary>
        internal static string DateAccessed {
            get {
                return ResourceManager.GetString("DateAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        internal static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        internal static string DateTaken {
            get {
                return ResourceManager.GetString("DateTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DefaultImage {
            get {
                object obj = ResourceManager.GetObject("DefaultImage", resourceCulture);
                if (obj is System.Drawing.Bitmap bitmap) {
                    return bitmap;
                }
                return CreateDefaultImage();
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        internal static string Dimensions {
            get {
                return ResourceManager.GetString("Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragDropCursor_Copy {
            get {
                object obj = ResourceManager.GetObject("DragDropCursor_Copy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragDropCursor_Move {
            get {
                object obj = ResourceManager.GetObject("DragDropCursor_Move", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DragDropCursor_No {
            get {
                object obj = ResourceManager.GetObject("DragDropCursor_No", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EmptyRatingImage {
            get {
                object obj = ResourceManager.GetObject("EmptyRatingImage", resourceCulture);
                if (obj is System.Drawing.Bitmap bitmap) {
                    return bitmap;
                }
                return CreateStarImage(false);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        internal static string EquipmentModel {
            get {
                return ResourceManager.GetString("EquipmentModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ErrorImage {
            get {
                object obj = ResourceManager.GetObject("ErrorImage", resourceCulture);
                if (obj is System.Drawing.Bitmap bitmap) {
                    return bitmap;
                }
                return CreateErrorImage();
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure Time.
        /// </summary>
        internal static string ExposureTime {
            get {
                return ResourceManager.GetString("ExposureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        internal static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F Number.
        /// </summary>
        internal static string FNumber {
            get {
                return ResourceManager.GetString("FNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focal Length.
        /// </summary>
        internal static string FocalLength {
            get {
                return ResourceManager.GetString("FocalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ImageDescription {
            get {
                return ResourceManager.GetString("ImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO Speed.
        /// </summary>
        internal static string ISOSpeed {
            get {
                return ResourceManager.GetString("ISOSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RatingImage {
            get {
                object obj = ResourceManager.GetObject("RatingImage", resourceCulture);
                if (obj is System.Drawing.Bitmap bitmap) {
                    return bitmap;
                }
                return CreateStarImage(true);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution.
        /// </summary>
        internal static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutter Speed.
        /// </summary>
        internal static string ShutterSpeed {
            get {
                return ResourceManager.GetString("ShutterSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software.
        /// </summary>
        internal static string Software {
            get {
                return ResourceManager.GetString("Software", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SortAscending {
            get {
                object obj = ResourceManager.GetObject("SortAscending", resourceCulture);
                if (obj is System.Drawing.Bitmap bitmap) {
                    return bitmap;
                }
                return CreateSortArrowImage(true);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SortDescending {
            get {
                object obj = ResourceManager.GetObject("SortDescending", resourceCulture);
                if (obj is System.Drawing.Bitmap bitmap) {
                    return bitmap;
                }
                return CreateSortArrowImage(false);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string UserComment {
            get {
                return ResourceManager.GetString("UserComment", resourceCulture);
            }
        }

        private static Bitmap CreateDefaultImage() {
            Bitmap bitmap = new Bitmap(32, 32);
            using (Graphics graphics = Graphics.FromImage(bitmap)) {
                graphics.Clear(Color.FromArgb(48, 48, 48));
                using (Pen borderPen = new Pen(Color.FromArgb(96, 96, 96))) {
                    graphics.DrawRectangle(borderPen, 0, 0, bitmap.Width - 1, bitmap.Height - 1);
                }
                using (Pen linePen = new Pen(Color.FromArgb(140, 140, 140), 2f)) {
                    graphics.DrawLine(linePen, 8, 23, 15, 14);
                    graphics.DrawLine(linePen, 15, 14, 20, 18);
                    graphics.DrawLine(linePen, 20, 18, 25, 10);
                }
            }
            return bitmap;
        }

        private static Bitmap CreateErrorImage() {
            Bitmap bitmap = new Bitmap(32, 32);
            using (Graphics graphics = Graphics.FromImage(bitmap)) {
                graphics.Clear(Color.FromArgb(48, 48, 48));
                using (Brush brush = new SolidBrush(Color.FromArgb(192, 57, 43))) {
                    graphics.FillEllipse(brush, 4, 4, 24, 24);
                }
                using (Pen pen = new Pen(Color.White, 3f)) {
                    graphics.DrawLine(pen, 10, 10, 22, 22);
                    graphics.DrawLine(pen, 22, 10, 10, 22);
                }
            }
            return bitmap;
        }

        private static Bitmap CreateSortArrowImage(bool ascending) {
            Bitmap bitmap = new Bitmap(8, 8);
            using (Graphics graphics = Graphics.FromImage(bitmap)) {
                graphics.Clear(Color.Transparent);
                Point[] points = ascending
                    ? new [] { new Point(4, 1), new Point(1, 6), new Point(7, 6) }
                    : new [] { new Point(1, 1), new Point(7, 1), new Point(4, 6) };
                using (Brush brush = new SolidBrush(Color.FromArgb(228, 228, 228))) {
                    graphics.FillPolygon(brush, points);
                }
            }
            return bitmap;
        }

        private static Bitmap CreateStarImage(bool filled) {
            Bitmap bitmap = new Bitmap(13, 13);
            using (Graphics graphics = Graphics.FromImage(bitmap)) {
                graphics.Clear(Color.Transparent);
                PointF[] points = new [] {
                    new PointF(6.5f, 0.8f),
                    new PointF(8.1f, 4.5f),
                    new PointF(12.1f, 4.9f),
                    new PointF(9.1f, 7.6f),
                    new PointF(10.0f, 11.8f),
                    new PointF(6.5f, 9.7f),
                    new PointF(3.0f, 11.8f),
                    new PointF(3.9f, 7.6f),
                    new PointF(0.9f, 4.9f),
                    new PointF(4.9f, 4.5f)
                };
                if (filled) {
                    using (Brush brush = new SolidBrush(Color.Gold)) {
                        graphics.FillPolygon(brush, points);
                    }
                }
                using (Pen pen = new Pen(filled ? Color.Goldenrod : Color.Gray)) {
                    graphics.DrawPolygon(pen, points);
                }
            }
            return bitmap;
        }
    }
}
