//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AriadnaEntities : DbContext
    {
        public AriadnaEntities()
            : base("name=AriadnaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actors { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Director> Directors { get; set; }
        public virtual DbSet<Documentary> Documentaries { get; set; }
        public virtual DbSet<DocumentaryGenre> DocumentaryGenres { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameGenre> GameGenres { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<GenreOfDocumentary> GenreOfDocumentaries { get; set; }
        public virtual DbSet<GenreOfGame> GenreOfGames { get; set; }
        public virtual DbSet<GenreOfLibrary> GenreOfLibraries { get; set; }
        public virtual DbSet<Ignore> Ignores { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<LibraryAuthor> LibraryAuthors { get; set; }
        public virtual DbSet<LibraryGenre> LibraryGenres { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<MovieCast> MovieCasts { get; set; }
        public virtual DbSet<MovieDirector> MovieDirectors { get; set; }
        public virtual DbSet<MovieGenre> MovieGenres { get; set; }
    }
}
