//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documentary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documentary()
        {
            this.DocumentaryGenres = new HashSet<DocumentaryGenre>();
        }
    
        public int Id { get; set; }
        public string title { get; set; }
        public string title_original { get; set; }
        public int year { get; set; }
        public string file_path { get; set; }
        public byte[] poster { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> creation_time { get; set; }
        public Nullable<bool> want_to_see { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentaryGenre> DocumentaryGenres { get; set; }
    }
}
