//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryGenre
    {
        public int Id { get; set; }
        public int libraryId { get; set; }
        public int genreId { get; set; }
    
        public virtual GenreOfLibrary GenreOfLibrary { get; set; }
        public virtual Library Library { get; set; }
    }
}
