//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCast
    {
        public int Id { get; set; }
        public Nullable<int> movieId { get; set; }
        public Nullable<int> actorId { get; set; }
    
        public virtual Actor Actor { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
